name: Build & Deploy React App
on:
  push:
    branches:
      - hotfix/v0.1.3-beta
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout branch'
        uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: 'Npm Install'
        run: npm install
      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_TREE_API_URL=$REACT_APP_TREE_API_URL >> .env
          echo REACT_APP_KAKAO_API_KEY=$REACT_APP_KAKAO_API_KEY >> .env
        env:
          REACT_APP_TREE_API_URL: ${{ secrets.REACT_APP_TREE_API_URL }}
          REACT_APP_KAKAO_API_KEY: ${{ secrets.REACT_APP_KAKAO_API_KEY }}
      - name: 'Npm Build'
        run: npm run build
      - name: 'Deploy to S3'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          REACT_APP_KAKAO_API_KEY: ${{ secrets.REACT_APP_KAKAO_API_KEY }}
          SOURCE_DIR: 'build'
